version: '3.8'

services:
  # Web server to serve the application
  web-server:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - ./:/app:ro  # Mount project as read-only
    ports:
      - "8081:8080"
    command: python -m http.server 8080
    networks:
      - capture-network

  # Visual capture service
  visual-capture:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./screenshots:/app/screenshots  # Mount screenshots directory
    depends_on:
      - web-server
    environment:
      - BASE_URL=http://web-server:8080
    networks:
      - capture-network
    command: >
      sh -c "
        echo 'Waiting for web server to start...';
        sleep 5;
        python3 /app/capture-views.py
      "

networks:
  capture-network:
    driver: bridge